name: Run Python Scraper

on:
  schedule:
    # 0600, 1200, 1800 EST
    - cron: '0 11,17,23 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # install dependencies
      - name: Install dependencies
        run: |
          cd scraper
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # run scraper
      - name: Run scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          cd scraper
          python main.py